/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/signup": {
    /**
     * Signup
     * @description Create new user account and return JWT.
     */
    post: operations["signup_api_v1_auth_signup_post"];
  };
  "/api/v1/auth/login": {
    /**
     * Login
     * @description Authenticate and return JWT.
     */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/organizations": {
    /**
     * List Organizations
     * @description List organizations where user is owner or member.
     */
    get: operations["list_organizations_api_v1_organizations_get"];
    /**
     * Create Organization
     * @description Create new organization (portfolio). Owner role assigned.
     */
    post: operations["create_organization_api_v1_organizations_post"];
  };
  "/api/v1/organizations/properties": {
    /**
     * List Properties
     * @description List properties (optionally filtered by organization).
     */
    get: operations["list_properties_api_v1_organizations_properties_get"];
    /**
     * Create Property
     * @description Create property under organization.
     */
    post: operations["create_property_api_v1_organizations_properties_post"];
  };
  "/api/v1/data/import/preview": {
    /**
     * Import Preview
     * @description Preview CSV headers for column mapping. Returns headers and auto-detected mapping.
     */
    post: operations["import_preview_api_v1_data_import_preview_post"];
  };
  "/api/v1/data/import": {
    /**
     * Import Csv
     * @description Upload CSV with column mapping. Creates snapshot + rows.
     */
    post: operations["import_csv_api_v1_data_import_post"];
  };
  "/api/v1/data/snapshots": {
    /**
     * List Snapshots
     * @description List data snapshots for user's properties.
     */
    get: operations["list_snapshots_api_v1_data_snapshots_get"];
  };
  "/api/v1/data/health-summary": {
    /**
     * Health Summary
     * @description Data health rollup across properties, or per-property when property_id given.
     */
    get: operations["health_summary_api_v1_data_health_summary_get"];
  };
  "/api/v1/jobs/engine-a": {
    /**
     * Trigger Engine A
     * @description Trigger Engine A (tactical 0-30 days) run.
     */
    post: operations["trigger_engine_a_api_v1_jobs_engine_a_post"];
  };
  "/api/v1/jobs/engine-b": {
    /**
     * Trigger Engine B
     * @description Trigger Engine B (strategic 31-365 days) run.
     */
    post: operations["trigger_engine_b_api_v1_jobs_engine_b_post"];
  };
  "/api/v1/jobs/status/{job_id}": {
    /**
     * Job Status
     * @description Get job status - poll for progress.
     */
    get: operations["job_status_api_v1_jobs_status__job_id__get"];
  };
  "/api/v1/jobs/training": {
    /**
     * Trigger Training
     * @description Trigger training job for property - builds dataset, trains, registers model.
     */
    post: operations["trigger_training_api_v1_jobs_training_post"];
  };
  "/api/v1/engines/runs": {
    /**
     * List Engine Runs
     * @description List engine runs for user's properties (owner, GM, or Analyst).
     */
    get: operations["list_engine_runs_api_v1_engines_runs_get"];
  };
  "/api/v1/engines/runs/{run_id}": {
    /**
     * Get Engine Run
     * @description Get engine run with recommendations.
     */
    get: operations["get_engine_run_api_v1_engines_runs__run_id__get"];
  };
  "/api/v1/engines/recommendations/{rec_id}/apply": {
    /**
     * Mark Recommendation Applied
     * @description Mark recommendation as applied. Owner and GM can approve; Analyst cannot.
     */
    post: operations["mark_recommendation_applied_api_v1_engines_recommendations__rec_id__apply_post"];
  };
  "/api/v1/contribution/summary": {
    /**
     * Contribution Summary
     * @description Projected incremental revenue vs baseline.
     * Realized: from applied recommendations, or from imported actuals when available.
     */
    get: operations["contribution_summary_api_v1_contribution_summary_get"];
  };
  "/api/v1/contribution/top-wins": {
    /**
     * Top Wins
     * @description Top opportunities by delta.
     */
    get: operations["top_wins_api_v1_contribution_top_wins_get"];
  };
  "/api/v1/contribution/avoided-losses": {
    /**
     * Avoided Losses
     * @description Recommendations we did NOT apply that would have lowered revenue.
     * Avoided losses = delta_dollars < 0, applied = false.
     */
    get: operations["avoided_losses_api_v1_contribution_avoided_losses_get"];
  };
  "/api/v1/exports/contribution.csv": {
    /**
     * Export Contribution Csv
     * @description CSV export for finance - contribution report.
     */
    get: operations["export_contribution_csv_api_v1_exports_contribution_csv_get"];
  };
  "/api/v1/exports/contribution.pdf": {
    /**
     * Export Contribution Pdf
     * @description PDF monthly performance and contribution report - well structured.
     */
    get: operations["export_contribution_pdf_api_v1_exports_contribution_pdf_get"];
  };
  "/api/v1/exports/contribution.html": {
    /**
     * Export Contribution Html
     * @description HTML contribution report - clean, printable structure.
     */
    get: operations["export_contribution_html_api_v1_exports_contribution_html_get"];
  };
  "/api/v1/alerts": {
    /**
     * List Alerts
     * @description Property-level inbox + portfolio rollup.
     */
    get: operations["list_alerts_api_v1_alerts_get"];
  };
  "/api/v1/alerts/{alert_id}/acknowledge": {
    /**
     * Acknowledge Alert
     * @description Mark alert as acknowledged.
     */
    post: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post"];
  };
  "/api/v1/properties/{property_id}/settings": {
    /**
     * Get Property Settings
     * @description Get property contract and guardrail settings.
     */
    get: operations["get_property_settings_api_v1_properties__property_id__settings_get"];
    /**
     * Update Property Settings
     * @description Update property settings. Owner and GM can edit; Analyst cannot.
     */
    patch: operations["update_property_settings_api_v1_properties__property_id__settings_patch"];
  };
  "/api/v1/properties/{property_id}/events": {
    /**
     * List Property Events
     * @description List events for property (holidays, conferences, etc).
     */
    get: operations["list_property_events_api_v1_properties__property_id__events_get"];
    /**
     * Create Property Event
     * @description Add event (holiday, conference) affecting Engine B rates.
     */
    post: operations["create_property_event_api_v1_properties__property_id__events_post"];
  };
  "/api/v1/properties/{property_id}/events/{event_id}": {
    /**
     * Delete Property Event
     * @description Remove event.
     */
    delete: operations["delete_property_event_api_v1_properties__property_id__events__event_id__delete"];
  };
  "/api/v1/billing/invoice": {
    /**
     * Get Invoice
     * @description Monthly invoice-ready output: base fee + revenue share + audit trail.
     */
    get: operations["get_invoice_api_v1_billing_invoice_get"];
  };
  "/api/v1/billing/yoy": {
    /**
     * Yoy Report
     * @description Year-over-year reporting and trend summaries.
     */
    get: operations["yoy_report_api_v1_billing_yoy_get"];
  };
  "/api/v1/outcomes/import": {
    /**
     * Import Outcomes
     * @description Import outcomes/actuals CSV for forecast error tracking and model calibration.
     */
    post: operations["import_outcomes_api_v1_outcomes_import_post"];
  };
  "/api/v1/manual-data/entry": {
    /**
     * Manual Entry
     * @description Manual entry fallback for single or batch rows.
     */
    post: operations["manual_entry_api_v1_manual_data_entry_post"];
  };
  "/api/v1/portfolio/outlook": {
    /**
     * Portfolio Outlook
     * @description Rollups across properties: next 30/60/90 outlook. Cached.
     */
    get: operations["portfolio_outlook_api_v1_portfolio_outlook_get"];
  };
  "/api/v1/portfolio/forecast": {
    /**
     * Forecast Dashboard
     * @description Dedicated 30/60/90 forecast: occupancy, ADR, RevPAR, pickup.
     * Aggregates from latest Engine A (0-30d) and Engine B (31-90d) outputs.
     */
    get: operations["forecast_dashboard_api_v1_portfolio_forecast_get"];
  };
  "/api/v1/portfolio/alerts-rollup": {
    /**
     * Alerts Rollup
     * @description Alerts rollup for portfolio.
     */
    get: operations["alerts_rollup_api_v1_portfolio_alerts_rollup_get"];
  };
  "/api/v1/portfolio/value-rollup": {
    /**
     * Value Rollup
     * @description RateMaster value generated rollup. Cached.
     */
    get: operations["value_rollup_api_v1_portfolio_value_rollup_get"];
  };
  "/api/v1/market/snapshot": {
    /**
     * Create Market Snapshot
     * @description Store market snapshot (manual entry or from adapter).
     */
    post: operations["create_market_snapshot_api_v1_market_snapshot_post"];
  };
  "/api/v1/market/snapshots": {
    /**
     * List Market Snapshots
     * @description List market snapshots for property.
     */
    get: operations["list_market_snapshots_api_v1_market_snapshots_get"];
  };
  "/api/v1/market/import-csv": {
    /**
     * Import Market Csv
     * @description Import market/rate-shop CSV. Columns: stay_date or date, compset_avg or adr.
     */
    post: operations["import_market_csv_api_v1_market_import_csv_post"];
  };
  "/api/v1/organizations/members": {
    /**
     * List Org Members
     * @description List members of an organization. Owner or member can list.
     */
    get: operations["list_org_members_api_v1_organizations_members_get"];
    /**
     * Invite Member
     * @description Invite user to org as GM or Analyst. Only owner can invite.
     */
    post: operations["invite_member_api_v1_organizations_members_post"];
  };
  "/api/v1/organizations/my-role": {
    /**
     * Get My Role
     * @description Get current user's role in organization.
     */
    get: operations["get_my_role_api_v1_organizations_my_role_get"];
  };
  "/api/v1/organizations/members/{member_id}": {
    /**
     * Remove Member
     * @description Remove member from org. Only owner can remove.
     */
    delete: operations["remove_member_api_v1_organizations_members__member_id__delete"];
  };
  "/api/v1/organizations/members/{member_id}/role": {
    /**
     * Update Member Role
     * @description Change member role (gm/analyst). Only owner can change.
     */
    patch: operations["update_member_role_api_v1_organizations_members__member_id__role_patch"];
  };
  "/api/v1/model-registry/models": {
    /**
     * List Models
     * @description List registered models - optionally filtered by property.
     */
    get: operations["list_models_api_v1_model_registry_models_get"];
  };
  "/api/v1/model-registry/models/{model_id}/activate": {
    /**
     * Activate Model
     * @description Activate a model version (rollback). Deactivates other versions with same model_name and property.
     */
    post: operations["activate_model_api_v1_model_registry_models__model_id__activate_post"];
  };
  "/health": {
    /**
     * Health
     * @description Health check.
     */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_create_market_snapshot_api_v1_market_snapshot_post */
    Body_create_market_snapshot_api_v1_market_snapshot_post: {
      /** Property Id */
      property_id: string;
      /** Compset Avg */
      compset_avg?: number | null;
      /** Compset Min */
      compset_min?: number | null;
      /** Compset Max */
      compset_max?: number | null;
      /**
       * Source
       * @default manual
       */
      source?: string;
      /** Stay Date */
      stay_date?: string | null;
    };
    /** Body_import_csv_api_v1_data_import_post */
    Body_import_csv_api_v1_data_import_post: {
      /** Property Id */
      property_id: string;
      /**
       * Snapshot Type
       * @default current
       */
      snapshot_type?: string;
      /** File */
      file: string;
      /**
       * Column Mapping
       * @default
       */
      column_mapping?: string;
      /**
       * Snapshot Date
       * @default
       */
      snapshot_date?: string;
    };
    /** Body_import_market_csv_api_v1_market_import_csv_post */
    Body_import_market_csv_api_v1_market_import_csv_post: {
      /** Property Id */
      property_id: string;
      /** File */
      file: string;
    };
    /** Body_import_outcomes_api_v1_outcomes_import_post */
    Body_import_outcomes_api_v1_outcomes_import_post: {
      /** Property Id */
      property_id: string;
      /** File */
      file: string;
    };
    /** Body_import_preview_api_v1_data_import_preview_post */
    Body_import_preview_api_v1_data_import_preview_post: {
      /** File */
      file: string;
    };
    /**
     * DataSnapshotResponse
     * @description Data snapshot response.
     */
    DataSnapshotResponse: {
      /** Id */
      id: string;
      /** Property Id */
      property_id: string;
      /** Snapshot Date */
      snapshot_date: string | null;
      /** Snapshot Type */
      snapshot_type: string;
      /** Row Count */
      row_count: number;
      /** Data Health Score */
      data_health_score: number | null;
      /** Created At */
      created_at: string;
      /** Recommended Fixes */
      recommended_fixes?: string[] | null;
    };
    /** EngineRunDetailResponse */
    EngineRunDetailResponse: {
      /** Id */
      id: string;
      /** Property Id */
      property_id: string;
      /** Engine Type */
      engine_type: string;
      /** Run Id */
      run_id: string;
      /** Status */
      status: string;
      /** Confidence */
      confidence: number | null;
      /** Created At */
      created_at: string;
      /** Recommendations */
      recommendations?: components["schemas"]["RecommendationResponse"][] | null;
      /** Calendar */
      calendar?: {
          [key: string]: unknown;
        }[] | null;
    };
    /** EngineRunResponse */
    EngineRunResponse: {
      /** Id */
      id: string;
      /** Property Id */
      property_id: string;
      /** Engine Type */
      engine_type: string;
      /** Run Id */
      run_id: string;
      /** Status */
      status: string;
      /** Confidence */
      confidence: number | null;
      /** Created At */
      created_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InviteMemberRequest */
    InviteMemberRequest: {
      /** Organization Id */
      organization_id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Role */
      role: string;
    };
    /**
     * LoginRequest
     * @description User login request.
     */
    LoginRequest: {
      /**
       * Email
       * Format: email
       * @description User email
       */
      email: string;
      /**
       * Password
       * @description Password
       */
      password: string;
    };
    /** ManualEntryRequest */
    ManualEntryRequest: {
      /** Property Id */
      property_id: string;
      /**
       * Snapshot Type
       * @default current
       */
      snapshot_type?: string;
      /** Rows */
      rows: components["schemas"]["ManualRow"][];
    };
    /** ManualRow */
    ManualRow: {
      /**
       * Stay Date
       * @description YYYY-MM-DD
       */
      stay_date: string;
      /** Rooms Available */
      rooms_available?: number | null;
      /** Total Rooms */
      total_rooms?: number | null;
      /** Rooms Sold */
      rooms_sold?: number | null;
      /** Adr */
      adr?: number | null;
      /** Total Rate */
      total_rate?: number | null;
      /** Revenue */
      revenue?: number | null;
    };
    /**
     * OrganizationCreate
     * @description Create organization request.
     */
    OrganizationCreate: {
      /** Name */
      name: string;
    };
    /**
     * OrganizationResponse
     * @description Organization response.
     */
    OrganizationResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * PropertyCreate
     * @description Create property request.
     */
    PropertyCreate: {
      /** Name */
      name: string;
      /**
       * Organization Id
       * @description Parent organization ID
       */
      organization_id: string;
    };
    /** PropertyEventCreate */
    PropertyEventCreate: {
      /**
       * Event Date
       * Format: date
       */
      event_date: string;
      /**
       * Event Type
       * @default holiday
       */
      event_type?: string;
      /**
       * Multiplier
       * @default 1.1
       */
      multiplier?: number;
      /** Name */
      name?: string | null;
    };
    /**
     * PropertyResponse
     * @description Property response.
     */
    PropertyResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** PropertySettingsUpdate */
    PropertySettingsUpdate: {
      /** Flow Through Pct */
      flow_through_pct?: number | string | null;
      /** Base Monthly Fee */
      base_monthly_fee?: number | string | null;
      /** Revenue Share Pct */
      revenue_share_pct?: number | string | null;
      /** Revenue Share On Gop */
      revenue_share_on_gop?: boolean | null;
      /** Contract Effective From */
      contract_effective_from?: string | null;
      /** Contract Effective To */
      contract_effective_to?: string | null;
      /** Min Bar */
      min_bar?: number | string | null;
      /** Max Bar */
      max_bar?: number | string | null;
      /** Max Daily Change Pct */
      max_daily_change_pct?: number | string | null;
      /** Blackout Dates */
      blackout_dates?: string[] | null;
      /** Dow Rules */
      dow_rules?: {
        [key: string]: unknown;
      } | null;
      /** Min Confidence Threshold */
      min_confidence_threshold?: number | null;
      /** Market Refresh Minutes */
      market_refresh_minutes?: number | null;
    };
    /** RecommendationResponse */
    RecommendationResponse: {
      /** Id */
      id: string;
      /** Stay Date */
      stay_date: string;
      /** Suggested Bar */
      suggested_bar: number | null;
      /** Current Bar */
      current_bar: number | null;
      /** Delta Dollars */
      delta_dollars: number | null;
      /** Delta Pct */
      delta_pct: number | null;
      /** Occupancy Projection */
      occupancy_projection: number | null;
      /** Occupancy Projection Low */
      occupancy_projection_low?: number | null;
      /** Occupancy Projection High */
      occupancy_projection_high?: number | null;
      /** Confidence */
      confidence: number | null;
      /** Why Bullets */
      why_bullets: string[] | null;
      /** Applied */
      applied: boolean;
    };
    /**
     * SignupRequest
     * @description User signup request.
     */
    SignupRequest: {
      /**
       * Email
       * Format: email
       * @description User email
       */
      email: string;
      /**
       * Password
       * @description Password
       */
      password: string;
    };
    /**
     * TokenResponse
     * @description JWT token response.
     */
    TokenResponse: {
      /**
       * Access Token
       * @description JWT access token
       */
      access_token: string;
      /**
       * Token Type
       * @description Token type
       * @default bearer
       */
      token_type?: string;
      /**
       * Expires In
       * @description Seconds until expiry
       */
      expires_in: number;
    };
    /** TriggerEngineRequest */
    TriggerEngineRequest: {
      /** Property Id */
      property_id: string;
    };
    /** UpdateRoleRequest */
    UpdateRoleRequest: {
      /** Role */
      role: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Signup
   * @description Create new user account and return JWT.
   */
  signup_api_v1_auth_signup_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Login
   * @description Authenticate and return JWT.
   */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Organizations
   * @description List organizations where user is owner or member.
   */
  list_organizations_api_v1_organizations_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationResponse"][];
        };
      };
    };
  };
  /**
   * Create Organization
   * @description Create new organization (portfolio). Owner role assigned.
   */
  create_organization_api_v1_organizations_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Properties
   * @description List properties (optionally filtered by organization).
   */
  list_properties_api_v1_organizations_properties_get: {
    parameters: {
      query?: {
        organization_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Property
   * @description Create property under organization.
   */
  create_property_api_v1_organizations_properties_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Preview
   * @description Preview CSV headers for column mapping. Returns headers and auto-detected mapping.
   */
  import_preview_api_v1_data_import_preview_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_preview_api_v1_data_import_preview_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Csv
   * @description Upload CSV with column mapping. Creates snapshot + rows.
   */
  import_csv_api_v1_data_import_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_csv_api_v1_data_import_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DataSnapshotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Snapshots
   * @description List data snapshots for user's properties.
   */
  list_snapshots_api_v1_data_snapshots_get: {
    parameters: {
      query?: {
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DataSnapshotResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health Summary
   * @description Data health rollup across properties, or per-property when property_id given.
   */
  health_summary_api_v1_data_health_summary_get: {
    parameters: {
      query?: {
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trigger Engine A
   * @description Trigger Engine A (tactical 0-30 days) run.
   */
  trigger_engine_a_api_v1_jobs_engine_a_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TriggerEngineRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trigger Engine B
   * @description Trigger Engine B (strategic 31-365 days) run.
   */
  trigger_engine_b_api_v1_jobs_engine_b_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TriggerEngineRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Job Status
   * @description Get job status - poll for progress.
   */
  job_status_api_v1_jobs_status__job_id__get: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trigger Training
   * @description Trigger training job for property - builds dataset, trains, registers model.
   */
  trigger_training_api_v1_jobs_training_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TriggerEngineRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Engine Runs
   * @description List engine runs for user's properties (owner, GM, or Analyst).
   */
  list_engine_runs_api_v1_engines_runs_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        engine_type?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EngineRunResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Engine Run
   * @description Get engine run with recommendations.
   */
  get_engine_run_api_v1_engines_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EngineRunDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Mark Recommendation Applied
   * @description Mark recommendation as applied. Owner and GM can approve; Analyst cannot.
   */
  mark_recommendation_applied_api_v1_engines_recommendations__rec_id__apply_post: {
    parameters: {
      path: {
        rec_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Contribution Summary
   * @description Projected incremental revenue vs baseline.
   * Realized: from applied recommendations, or from imported actuals when available.
   */
  contribution_summary_api_v1_contribution_summary_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        horizon_days?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Top Wins
   * @description Top opportunities by delta.
   */
  top_wins_api_v1_contribution_top_wins_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Avoided Losses
   * @description Recommendations we did NOT apply that would have lowered revenue.
   * Avoided losses = delta_dollars < 0, applied = false.
   */
  avoided_losses_api_v1_contribution_avoided_losses_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Contribution Csv
   * @description CSV export for finance - contribution report.
   */
  export_contribution_csv_api_v1_exports_contribution_csv_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        horizon_days?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Contribution Pdf
   * @description PDF monthly performance and contribution report - well structured.
   */
  export_contribution_pdf_api_v1_exports_contribution_pdf_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        horizon_days?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Contribution Html
   * @description HTML contribution report - clean, printable structure.
   */
  export_contribution_html_api_v1_exports_contribution_html_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        horizon_days?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Alerts
   * @description Property-level inbox + portfolio rollup.
   */
  list_alerts_api_v1_alerts_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        acknowledged?: boolean | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Acknowledge Alert
   * @description Mark alert as acknowledged.
   */
  acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post: {
    parameters: {
      path: {
        alert_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Property Settings
   * @description Get property contract and guardrail settings.
   */
  get_property_settings_api_v1_properties__property_id__settings_get: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Property Settings
   * @description Update property settings. Owner and GM can edit; Analyst cannot.
   */
  update_property_settings_api_v1_properties__property_id__settings_patch: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertySettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Property Events
   * @description List events for property (holidays, conferences, etc).
   */
  list_property_events_api_v1_properties__property_id__events_get: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Property Event
   * @description Add event (holiday, conference) affecting Engine B rates.
   */
  create_property_event_api_v1_properties__property_id__events_post: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PropertyEventCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Property Event
   * @description Remove event.
   */
  delete_property_event_api_v1_properties__property_id__events__event_id__delete: {
    parameters: {
      path: {
        property_id: string;
        event_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Invoice
   * @description Monthly invoice-ready output: base fee + revenue share + audit trail.
   */
  get_invoice_api_v1_billing_invoice_get: {
    parameters: {
      query: {
        property_id?: string | null;
        year: number;
        month: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Yoy Report
   * @description Year-over-year reporting and trend summaries.
   */
  yoy_report_api_v1_billing_yoy_get: {
    parameters: {
      query: {
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Outcomes
   * @description Import outcomes/actuals CSV for forecast error tracking and model calibration.
   */
  import_outcomes_api_v1_outcomes_import_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_outcomes_api_v1_outcomes_import_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Manual Entry
   * @description Manual entry fallback for single or batch rows.
   */
  manual_entry_api_v1_manual_data_entry_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManualEntryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Portfolio Outlook
   * @description Rollups across properties: next 30/60/90 outlook. Cached.
   */
  portfolio_outlook_api_v1_portfolio_outlook_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Forecast Dashboard
   * @description Dedicated 30/60/90 forecast: occupancy, ADR, RevPAR, pickup.
   * Aggregates from latest Engine A (0-30d) and Engine B (31-90d) outputs.
   */
  forecast_dashboard_api_v1_portfolio_forecast_get: {
    parameters: {
      query?: {
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Alerts Rollup
   * @description Alerts rollup for portfolio.
   */
  alerts_rollup_api_v1_portfolio_alerts_rollup_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Value Rollup
   * @description RateMaster value generated rollup. Cached.
   */
  value_rollup_api_v1_portfolio_value_rollup_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Create Market Snapshot
   * @description Store market snapshot (manual entry or from adapter).
   */
  create_market_snapshot_api_v1_market_snapshot_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_create_market_snapshot_api_v1_market_snapshot_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Market Snapshots
   * @description List market snapshots for property.
   */
  list_market_snapshots_api_v1_market_snapshots_get: {
    parameters: {
      query: {
        property_id: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Market Csv
   * @description Import market/rate-shop CSV. Columns: stay_date or date, compset_avg or adr.
   */
  import_market_csv_api_v1_market_import_csv_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_market_csv_api_v1_market_import_csv_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Org Members
   * @description List members of an organization. Owner or member can list.
   */
  list_org_members_api_v1_organizations_members_get: {
    parameters: {
      query: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Invite Member
   * @description Invite user to org as GM or Analyst. Only owner can invite.
   */
  invite_member_api_v1_organizations_members_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get My Role
   * @description Get current user's role in organization.
   */
  get_my_role_api_v1_organizations_my_role_get: {
    parameters: {
      query: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Remove Member
   * @description Remove member from org. Only owner can remove.
   */
  remove_member_api_v1_organizations_members__member_id__delete: {
    parameters: {
      path: {
        member_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Member Role
   * @description Change member role (gm/analyst). Only owner can change.
   */
  update_member_role_api_v1_organizations_members__member_id__role_patch: {
    parameters: {
      path: {
        member_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Models
   * @description List registered models - optionally filtered by property.
   */
  list_models_api_v1_model_registry_models_get: {
    parameters: {
      query?: {
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Activate Model
   * @description Activate a model version (rollback). Deactivates other versions with same model_name and property.
   */
  activate_model_api_v1_model_registry_models__model_id__activate_post: {
    parameters: {
      path: {
        model_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health
   * @description Health check.
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
